"""Create Auditorium, Slot, and Booking tables

Revision ID: a2eada6954a2
Revises: 66ae28c164c6
Create Date: 2024-12-04 10:15:21.332440

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a2eada6954a2'
down_revision: Union[str, None] = '66ae28c164c6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
