"""Created Booking tables

Revision ID: a3c1e7fe8aa7
Revises: a2eada6954a2
Create Date: 2024-12-04 10:23:35.036811

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a3c1e7fe8aa7'
down_revision: Union[str, None] = 'a2eada6954a2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_auditoriums_id', table_name='auditoriums')
    op.drop_index('ix_auditoriums_name', table_name='auditoriums')
    op.drop_constraint('slots_auditorium_id_fkey', 'slots', type_='foreignkey')
    op.drop_table('slots')
    op.drop_table('auditoriums')
    op.drop_index('ix_slots_auditorium_id', table_name='slots')
    op.drop_index('ix_slots_date', table_name='slots')
    op.drop_index('ix_slots_id', table_name='slots')
    op.drop_index('ix_slots_slot_name', table_name='slots')
    op.drop_table('slots')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('slots',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('auditorium_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('date', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('slot_name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('start_time', postgresql.TIME(), autoincrement=False, nullable=False),
    sa.Column('end_time', postgresql.TIME(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['auditorium_id'], ['auditoriums.id'], name='slots_auditorium_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='slots_pkey'),
    sa.UniqueConstraint('auditorium_id', 'date', 'start_time', name='unique_availability')
    )
    op.create_index('ix_slots_slot_name', 'slots', ['slot_name'], unique=False)
    op.create_index('ix_slots_id', 'slots', ['id'], unique=False)
    op.create_index('ix_slots_date', 'slots', ['date'], unique=False)
    op.create_index('ix_slots_auditorium_id', 'slots', ['auditorium_id'], unique=False)
    op.create_table('auditoriums',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('seating', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('booking_charge', sa.NUMERIC(precision=3, scale=2), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='auditoriums_pkey')
    )
    op.create_index('ix_auditoriums_name', 'auditoriums', ['name'], unique=False)
    op.create_index('ix_auditoriums_id', 'auditoriums', ['id'], unique=False)
    

    # ### end Alembic commands ###
